name: fruitproject
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^0.13.3
  provider: ^6.1.1
  dots_indicator: ^2.0.0
  font_awesome_flutter: ^9.0.0
  firebase_auth: ^3.3.3
  google_sign_in: 6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
