// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaZfarA93CEyOxMYSGppQPz6YhLNzO4ms',
    appId: '1:128728372681:web:03184b9cd1fa16226cc418',
    messagingSenderId: '128728372681',
    projectId: 'fruitproject-90db6',
    authDomain: 'fruitproject-90db6.firebaseapp.com',
    storageBucket: 'fruitproject-90db6.appspot.com',
    measurementId: 'G-VKM0MXBGD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYZvBKUTpFZaq5D3Nucn7t_EEqvF_htuM',
    appId: '1:128728372681:android:7f48941128addb3b6cc418',
    messagingSenderId: '128728372681',
    projectId: 'fruitproject-90db6',
    storageBucket: 'fruitproject-90db6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmuLKZat8-kDLXGuW-LpQEjrf_ksKnRl8',
    appId: '1:128728372681:ios:8fd1252cb24370486cc418',
    messagingSenderId: '128728372681',
    projectId: 'fruitproject-90db6',
    storageBucket: 'fruitproject-90db6.appspot.com',
    iosBundleId: 'com.example.fruitproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmuLKZat8-kDLXGuW-LpQEjrf_ksKnRl8',
    appId: '1:128728372681:ios:34e9e8316a847db16cc418',
    messagingSenderId: '128728372681',
    projectId: 'fruitproject-90db6',
    storageBucket: 'fruitproject-90db6.appspot.com',
    iosBundleId: 'com.example.fruitproject.RunnerTests',
  );
}
